### ISSUE TITLE
I cannot enable the extension

### ISSUE THREAD

**Issue by wmeitzen** [marttiphpbb/phpbb-ext-emaillogin#1]
Hi, I can't seem to enable the emaillogin extension.  I've provided some attachments..  Sorry if this is a common question, I couldn't find where it's been asked before.  Thank you!

![attachment-3](https://user-images.githubusercontent.com/13643084/69012144-20b87700-0938-11ea-8da0-44328db6ab75.jpg)
![attachment-1](https://user-images.githubusercontent.com/13643084/69012145-20b87700-0938-11ea-8fd3-e48ffadbe714.jpg)
![attachment-2](https://user-images.githubusercontent.com/13643084/69012146-20b87700-0938-11ea-93e8-1c23289eaa4c.jpg)

**Comment by marttiphpbb** [comment]
The message says to review [the requirements](https://github.com/marttiphpbb/phpbb-ext-emaillogin).  Don't they match your installation? What's your PHP and phpBB version?

**Comment by wmeitzen** [comment]
I was using an old version of PHP.  It's fixed now.  Thanks.
